# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.Pregunta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together=set([('user', 'question')]),
        ),
    ]
