# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0002_auto_20170819_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuestas.Pregunta'),
        ),
    ]
